// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_VsH9vuT7RTyWNqbmjpV64us4HpD2qqM',
    appId: '1:1079317840093:web:a7f0a7ba61330344ff5b34',
    messagingSenderId: '1079317840093',
    projectId: 'univproject-964ba',
    authDomain: 'univproject-964ba.firebaseapp.com',
    storageBucket: 'univproject-964ba.appspot.com',
    measurementId: 'G-VBRP1MYKVS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSs1Ctcup8SCl4qas6Kcg7if3F82Ihpjk',
    appId: '1:1079317840093:android:d3fb1b942f83f13dff5b34',
    messagingSenderId: '1079317840093',
    projectId: 'univproject-964ba',
    storageBucket: 'univproject-964ba.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAHItCAtZJdYB6yMk7zGytbROUhX0pP6dI',
    appId: '1:1079317840093:ios:a608b6c46444596dff5b34',
    messagingSenderId: '1079317840093',
    projectId: 'univproject-964ba',
    storageBucket: 'univproject-964ba.appspot.com',
    iosBundleId: 'com.example.univproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAHItCAtZJdYB6yMk7zGytbROUhX0pP6dI',
    appId: '1:1079317840093:ios:a608b6c46444596dff5b34',
    messagingSenderId: '1079317840093',
    projectId: 'univproject-964ba',
    storageBucket: 'univproject-964ba.appspot.com',
    iosBundleId: 'com.example.univproject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD_VsH9vuT7RTyWNqbmjpV64us4HpD2qqM',
    appId: '1:1079317840093:web:bc08a533f0fa8971ff5b34',
    messagingSenderId: '1079317840093',
    projectId: 'univproject-964ba',
    authDomain: 'univproject-964ba.firebaseapp.com',
    storageBucket: 'univproject-964ba.appspot.com',
    measurementId: 'G-VBE3X9SJJ0',
  );

}